volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      retries: 5

  backend:
    container_name: foodgram-back
    image: athletev/foodgram_backend
    command: /bin/sh -c "chmod +x ./load.sh && ./load.sh && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/static
      - media:/app/media
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: foodgram-front
    image: athletev/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    image: athletev/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - frontend
      - backend
